# Generated by Django 4.0.6 on 2022-08-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_service_send_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
