# Generated by Django 4.0.6 on 2022-08-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ssl_properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
