# Generated by Django 4.0.6 on 2022-08-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='send_notification',
            field=models.BooleanField(default=True),
        ),
    ]
