# Generated by Django 4.0.6 on 2022-08-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_alter_service_ssl_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
