# Generated by Django 4.0.6 on 2022-08-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_service_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
