# Generated by Django 4.0.6 on 2022-08-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_alter_service_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
